import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/app/myComponents/header";
import { AuthProvider } from "./contexts/AuthContext";
//import Footer from "./myComponents/footer";
import { GuicheProvider } from "./contexts/guicheContext";
import { TotalSenhasProvider } from "./contexts/totalSenhasContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gerênciador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden bg-[#ebeff5]`}
      >
        <AuthProvider>
          <GuicheProvider>
            <TotalSenhasProvider>
              <div className="flex flex-col min-h-screen max-h-screen overflow-hidden">
                <Header />
                <main className="flex-grow overflow-hidden flex items-center justify-center">
                  <div className="w-full h-full scale-95  mb-8">{children}</div>
                </main>
              </div>
            </TotalSenhasProvider>
          </GuicheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
